# Generated by Django 3.2.8 on 2021-10-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400)),
                ('done', models.BooleanField()),
                ('created_at', models.CharField(max_length=25)),
                ('updated_at', models.CharField(max_length=25)),
            ],
        ),
    ]
