# Generated by Django 3.2.8 on 2021-10-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
    ]
