# Generated by Django 3.2.8 on 2021-10-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_remove_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
