# Generated by Django 3.2.8 on 2021-10-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_todo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
    ]
