# Generated by Django 3.2.8 on 2021-10-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_remove_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
